export const tzData = [
  {
    taskId: 1,
    taskTitle: "Easy",
    taskTitleHeight: 0,
    taskDone: true,
    taskOpened: true,
    taskHovered: false,
    subMenuShown: false,
    subMenuX: 0,
    subMenuY: 0,
    editReady: false,
    taskSubs: [
      {
        taskId: 4,
        taskTitle:
          "Каждая новая вкладка в браузере с приложением - отдельный проект со своим списком задач",
        taskTitleHeight: 0,
        taskDone: true,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 3,
        taskTitle:
          "Редактируемое название проекта в качестве заголовка страницы",
        taskTitleHeight: 0,
        taskDone: true,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: true,
        taskSubs: [],
      },
      {
        taskId: 2,
        taskTitle: "Добавление новой задачи в список",
        taskTitleHeight: 0,
        taskDone: true,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 12,
        taskTitle: "Удаление любой задачи из списка",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 13,
        taskTitle:
          "Возможность пометить любую задачу сделанной и возможность убрать эту пометку",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 14,
        taskTitle:
          "Вся информация (название проекта, список задач, состояние задач) должна сохраняться при перезагрузке страницы",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 15,
        taskTitle: "Возможность добавлять подзадачи в любую задачу",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 16,
        taskTitle: "Поле ввода для поиска/фильтрации задач в списке",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 17,
        taskTitle:
          "Возможность редактирования названия задачи после её создания",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
    ],
  },
  {
    taskId: 18,
    taskTitle: "Medium",
    taskTitleHeight: 0,
    taskDone: false,
    taskOpened: true,
    taskHovered: false,
    subMenuShown: false,
    subMenuX: 487.95001220703125,
    subMenuY: 809.8000030517578,
    editReady: false,
    taskSubs: [
      {
        taskId: 19,
        taskTitle:
          "Возможность перемещать любые задачи (со всем списком подзадач) из любого открытого проекта в любой другой открытый проект",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 20,
        taskTitle:
          "Нельзя использовать LocalStorage, Cookies, IndexedDB и WebSQL хранилища",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 21,
        taskTitle: "Экспорт проекта в файл / импорт проекта из файла",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 22,
        taskTitle:
          "Имя сохраняемого файла должно соответствовать названию проекта",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 23,
        taskTitle: "Drag-n-drop для перемещения задач в списке;",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 24,
        taskTitle:
          "Сохранение текущего фильтра для возможности его быстрого применения потом",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 25,
        taskTitle: "Наличие CSS-анимаций для drag-n-drop и фильтрации задач",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 26,
        taskTitle:
          "Использовать TypeScript для 100% кодовой базы (исключая вёрстку и стили)",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 27,
        taskTitle: "Использовать Vue Composition API или vue@next",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 28,
        taskTitle: "Использовать ESLint/TSLint для контроля качества кода",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 29,
        taskTitle:
          "Использовать сборщик/бандлер (например, webpack) для сборки приложения в SPA",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 30,
        taskTitle: "Итоговое приложение должно весить не более 200 KB",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
    ],
  },
  {
    taskId: 31,
    taskTitle: "Hard",
    taskTitleHeight: 0,
    taskDone: false,
    taskOpened: true,
    taskHovered: false,
    subMenuShown: false,
    subMenuX: 809.9500122070312,
    subMenuY: 1703,
    editReady: false,
    taskSubs: [
      {
        taskId: 32,
        taskTitle: "Drag-n-drop с поддержкой тач-скрина",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 33,
        taskTitle:
          "Масштабируемость на мобильные устройства до 320*480px (iPhone 4)",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 34,
        taskTitle:
          "Возможность быстрого просмотра и редактирования описания у любой задачи",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 35,
        taskTitle: "SSR",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 36,
        taskTitle: "PWA",
        taskTitleHeight: 0,
        taskDone: true,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 37,
        taskTitle: "Опция фильтрации задач по RegExp",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
      {
        taskId: 38,
        taskTitle:
          "Возможность добавлять/удалять именованные списки для задач, между которыми их можно перетаскивать (как в trello)",
        taskTitleHeight: 0,
        taskDone: false,
        taskOpened: false,
        taskHovered: false,
        subMenuShown: false,
        subMenuX: 0,
        subMenuY: 0,
        editReady: false,
        taskSubs: [],
      },
    ],
  },
  {
    projectName: "ТЗ тестового задания",
  },
];
